.travis.yml
Partly related to #45.
This adds PEP8 and pyflakes testing.
flake8 helps find simple bugs, see 7629461bc2.
However, we sometimes intentionally break PEP8 rules.
I do not want to add exceptions for each case, nor ignore all those rules entirely.
Perhaps just report the results from flake8 but ignore the returned status?
=> Add flake8 testing

.travis.yml, sapphire/analysis/core_reconstruction.py, sapphire/analysis/direction_reconstruction.py, sapphire/analysis/reconstructions.py, sapphire/api.py, sapphire/clusters.py, sapphire/tests/analysis/test_direction_reconstruction.py, sapphire/tests/analysis/test_event_utils.py, sapphire/tests/test_api.py, sapphire/tests/test_clusters.py, sapphire/tests/test_clusters_acceptance.py, sapphire/tests/test_utils.py, sapphire/tests/transformations/test_axes.py, sapphire/transformations/axes.py, sapphire/utils.py
PR for #63.
Add time awareness to Cluster objects. Allow setting a 'timestamps' and get station/detector positions relevant for that timestamp.
Todo:
=> 4 dimensional stations

sapphire/tests/analysis/test_landau.py
Fix PEP8 in master: remove unused imports:
$ flake8 --ignore=E501 --exclude=sapphire/transformations/geographic.py sapphire
sapphire/tests/analysis/test_landau.py:2:1: F401 'warnings' imported but unused
sapphire/tests/analysis/test_landau.py:4:1: F401 'array' imported but unused
=> Fix PEP8 in master: remove unused imports

sapphire/esd.py
On a successful download the last line should be a non-empty comment line.
If the last line is indeed a non-empty comment, do nothing.
If it is not raise an exception.
If the last line was an empty comment only the header was downloaded.
If the last line is data report the date/time of that data.
Related to HiSPARC/publicdb#128
TODO:
- Update tests to test failure
- If someone feels adventurous they can try to make the script start downloading again if it fully/partially failed.
=> Add support for the end status line for downloading

.travis.yml
These packages are not required by conda packages
=> Travis without apt-get

sapphire/analysis/direction_reconstruction.py
Fixes #131 
The regression algorithm was assumed to always converge.
In certain situations it does not.
Allow only a certain number of iterations before returning nan, nan.
Currently the maximum number of iterations is set to 1000.
ToDo:
=> Prevent infinite loop in regression

sapphire/__init__.py
Conversion of datetime to and from gps timestamps is a recurring task.
SAPPHiRE has well tested functions to do this. But they cumbersome to
import because they are in sapphire.transformations.clock
Allow:
```python
from sapphire import gps_to_datetime
from sapphire import datetime_to_gps
```
=> Add gps_to_datetime and datetime_to_gps to global __init__.py

sapphire/__init__.py, sapphire/analysis/calibration.py
`error = σ / √n` - https://en.wikipedia.org/wiki/Standard_error
Unlike the rchi2 used previously this correctly increases the error if the distribution becomes wider and the number of counts is reduced.
=> Use standard error of the mean for error of station timing offsets

sapphire/corsika/blocks.py
This is a bug fix for the `CorsikaFileThin` class in `corsika.reader`:
+ In `blocks.FormatThin` the format specifier for DATA blocks is wrongly inherited from the `blocks.Format` class. Consequently the read data are wrong when using thinning. => Fixed.
+ The additional weight parameter is not propagated to the end user. => Fix proposed in `corsika.blocks.particle_data`.
=> fix bug for reading thinned particles in CORSIKA

sapphire/tests/test_api.py
unittest.TestCase.assertEqual cannot compare (nan, nan) tuples.
This makes test_api.test_station_timing_offsets fail if station
501 has offsets (nan, nan).
To fix it use numpy.nan_to_num to replace nan by 0. This casts
the tuples to numpy.ndarrays which still cannot be compared.
Hence we cast this to list.
This is an ugly fix for a stupid problem... Perhaps use `numpy.testing.assert_equal` ?
=> Handle (nan,nan) station timing offset in tests

sapphire/analysis/event_utils.py, sapphire/tests/analysis/test_event_utils.py
sapphire.api.Station.detectors() was removed in 54dc4c9.
Fix usage of that method in get_detector_ids().
=> Fix get_detector_ids()

.travis.yml
CPython 3.6 was released 23-12-2016.
python 3.6 should be in conda defaults channel when Anaconda 4.3 is released.
(expected end of jan 2017)
Use python 3.6 packages from conda-forge
Use numba package from numba channel
=> Test against python 3.6

sapphire/tests/test_utils.py
Progressbar2 >=3.16 handles wrong length without raising ValueError.
Remove the unittest that tests against it.
=> Remove test_utils.test_pbar_generator_wrong_length

sapphire/analysis/time_deltas.py, sapphire/tests/test_utils.py
On Windows timedelta paths are messed up because `os.path.join` is used to concat paths, and this generates backslashes on Windows:
`/coincidences\time_deltas/station_1/station_2` etc.
Using `posixpath` solve this.
=> Fix timedelta path

sapphire/clusters.py, sapphire/tests/test_api.py, sapphire/tests/test_clusters.py
Set the center of mass of clusters (HiSPARCStation, HiSPARCNetwork,
ScienceParkCluster) to (0, 0, 0).
This is necessary for simulations, to make sure the clusters are rotated
around the correct axis.
=> Set the center of mass of clusters to (0,0,0).

sapphire/clusters.py, sapphire/tests/test_clusters.py
Handle rotated and translated clusters. Add test. Fixes some issues with #171.
Change set_center_of_mass_to_zero() to set_center_of_mass_at_origin()
=> Set center of masss to origin for rotated clusters

sapphire/clusters.py
sapphire.api.Station().gps_locations is an empty numpy.ndarray for stations
without GPS locations. This will trigger the correct exception in this case.
=> Fix HiSPARCStations for stations with missing GPS

sapphire/analysis/core_reconstruction.py
pycodestyle>=2.1.0 does not accept ambigious variable name 'l'. (E741).
flake8>=3.5 checks for E741.
=> Fix flake8 E741 ambiguous variable l

.travis.yml, Makefile, sapphire/analysis/calibration.py, sapphire/tests/transformations/test_axes.py, sapphire/transformations/axes.py, sapphire/transformations/geographic.py, setup.py
These issues showed up as warnings during tests.
> PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
> DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.
=> Deprecation fixes

sapphire/tests/validate_results.py
This should help fix the remaining test failure for publicdb;
https://github.com/153957/publicdb/runs/7297308865?check_suite_focus=true
Locally the tests work, but not in the pipelines, maybe because of some differences in deep level numpy/scipy dependencies.. mlk or whatever. But the results are close enough, so using almost equal comparison should be fine.
=> Be a bit more forgiving when comparing floats
